### ISSUE TITLE
No tables detected

### ISSUE THREAD

**Issue by aornugent** [ManyDesigns/Portofino#270]
Hia, this'll sound dumb but I'm not sure how to debug.

I'd like to demo Portofino as a Postgres GUI. I spun up a docker image and linked it to a database. Working through the connection wizard works fine. I add some tables, then go looking for them in Administration -> Tables, but the list comes up empty. Code below

```
#docker-compose.yml
version: '3.6'

services:
  portofino:
    image: manydesigns/portofino
    container_name: portofino_app
    depends_on:
      - db
    ports:
      - 8013:8080

  db:
    image: postgres:9.4-alpine
    container_name: portofino_postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - 8014:5432
    command: postgres
```
Then:
```
docker exec -it portofino_postgres /bin/ash
psql -U postgres -d postgres -c 'CREATE TABLE test (id serial);'
```
Connection URL:
```
jdbc:postgresql://db/postgres
```
which connects, detects the public schema and appears to synchronise ok, but finds no tables:

![image](https://user-images.githubusercontent.com/20387761/66967740-b492eb00-f0cd-11e9-8f60-0c93bb4c3148.png)
